-- ONLY run on https://supabase.com/dashboard/project/tgvozhrkolcpszyyrgth/sql
-- Fresh staging project only. Never run on production; never reset an existing database.
do $$
begin
  if to_regclass('public.gd_shop') is not null or exists(select 1 from auth.users) then raise exception 'STAGING_SETUP_REQUIRES_EMPTY_PROJECT'; end if;
end;
$$;

-- 202610090001_shop.sql
begin;
create schema if not exists gd_private;
revoke all on schema gd_private from public;

create table public.gd_admins (user_id uuid primary key references auth.users(id) on delete cascade);
alter table public.gd_admins enable row level security;
create policy admin_self on public.gd_admins for select to authenticated using (user_id = (select auth.uid()));
grant select on public.gd_admins to authenticated;
revoke insert, update, delete on public.gd_admins from anon, authenticated;
create function gd_private.is_admin() returns boolean language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.gd_admins where user_id = auth.uid());
$$;
grant usage on schema gd_private to authenticated;
grant execute on function gd_private.is_admin() to authenticated;
revoke execute on function gd_private.is_admin() from public, anon;

create table public.gd_shop (
  id integer primary key check (id = 1),
  name text not null check(length(name) between 2 and 80),
  phone text not null check(phone ~ '^(0|\+84)[35789][0-9]{8}$'),
  about text not null default '' check(length(about) <= 1000),
  accepting_orders boolean not null default false,
  cod_enabled boolean not null default true,
  transfer_enabled boolean not null default false,
  bank_bin text not null default '' check(bank_bin = '' or bank_bin ~ '^[0-9]{6}$'),
  bank_account text not null default '' check(bank_account = '' or bank_account ~ '^[0-9A-Za-z]{4,32}$'),
  bank_name text not null default '' check(length(bank_name) <= 80),
  account_name text not null default '' check(length(account_name) <= 100),
  version integer not null default 1,
  check(not transfer_enabled or (bank_bin <> '' and bank_account <> '' and account_name <> '')),
  check(not accepting_orders or cod_enabled or transfer_enabled)
);
insert into public.gd_shop(id,name,phone,about) values(1,'Garden Dreams','0832345780','Hoa mang lời thương.');
create table public.gd_products (
  id integer generated by default as identity primary key,
  name text not null check(length(name) between 2 and 100),
  occasion text not null check(occasion in ('Sinh nhật','Tình yêu','Chúc mừng','Cưới hỏi')),
  price integer not null check(price between 1000 and 100000000),
  stems text not null check(length(stems) <= 200),
  description text not null check(length(description) <= 1000),
  image text not null check(length(image) <= 500 and (image ~ '^/flowers/[a-zA-Z0-9_.-]+$' or image ~ '^https://')),
  active boolean not null default true,
  featured boolean not null default false,
  version integer not null default 1
);
create table public.gd_shipping (
  id uuid primary key default gen_random_uuid(),
  name text not null check(length(name) between 2 and 80),
  area text not null check(length(area) between 2 and 200),
  fee integer not null check(fee between 0 and 10000000),
  active boolean not null default false,
  version integer not null default 1
);
insert into public.gd_shipping(name,area,fee) values('Giao hoa theo lịch','Chưa cấu hình khu vực giao',0);
alter table public.gd_shop enable row level security;
alter table public.gd_products enable row level security;
alter table public.gd_shipping enable row level security;
create policy shop_read on public.gd_shop for select to anon, authenticated using (true);
create policy shop_admin on public.gd_shop for update to authenticated using (gd_private.is_admin()) with check (gd_private.is_admin());
create policy product_read on public.gd_products for select to anon, authenticated using(active or gd_private.is_admin());
create policy product_admin on public.gd_products for all to authenticated using(gd_private.is_admin()) with check(gd_private.is_admin());
create policy shipping_read on public.gd_shipping for select to anon, authenticated using(active or gd_private.is_admin());
create policy shipping_admin on public.gd_shipping for all to authenticated using(gd_private.is_admin()) with check(gd_private.is_admin());
grant select on public.gd_shop, public.gd_products, public.gd_shipping to anon, authenticated;
grant update on public.gd_shop to authenticated;
grant insert,update,delete on public.gd_products,public.gd_shipping to authenticated;
grant usage,select on sequence public.gd_products_id_seq to authenticated;
-- anon must be able to evaluate the read policy without accessing any admin rows.
grant usage on schema gd_private to anon;
grant execute on function gd_private.is_admin() to anon;

create table public.gd_orders (
  id uuid primary key,
  owner_id uuid not null references auth.users(id),
  reference text not null unique,
  request_body jsonb not null,
  recipient_name text,
  recipient_phone text,
  address text,
  card_message text not null default '',
  delivery_date date not null,
  delivery_time text not null,
  items jsonb not null,
  subtotal bigint not null check(subtotal >= 0),
  shipping jsonb not null,
  total bigint not null check(total >= 0),
  payment_method text not null check(payment_method in ('COD','VIETQR')),
  bank jsonb,
  status text not null default 'PENDING' check(status in ('PENDING','CONFIRMED','PREPARING','SHIPPING','DELIVERED','CANCELLED')),
  payment_status text not null default 'UNPAID' check(payment_status in ('UNPAID','PAID','REFUNDED')),
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  contacts_erased_at timestamptz
);
create index gd_orders_owner_cursor on public.gd_orders(owner_id, created_at desc, id desc);
create index gd_orders_admin_cursor on public.gd_orders(created_at desc, id desc);
create table public.gd_order_events (
  id bigint generated always as identity primary key,
  order_id uuid not null references public.gd_orders(id),
  actor_id uuid references auth.users(id),
  event text not null,
  note text not null default '',
  created_at timestamptz not null default now()
);
create index gd_events_order on public.gd_order_events(order_id,id);
create table public.gd_memories (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.gd_orders(id),
  owner_id uuid not null references auth.users(id),
  message text not null default '',
  signature text not null default '' check(length(signature) <= 80),
  flower_name text not null,
  flower_image text not null,
  share_token uuid unique,
  listed boolean not null default false,
  revoked boolean not null default false,
  created_at timestamptz not null default now(),
  check(not listed or share_token is not null)
);
create index gd_memories_garden_cursor on public.gd_memories(created_at desc,id desc) where listed and not revoked;
create index gd_memories_owner on public.gd_memories(owner_id,created_at desc,id desc);
alter table public.gd_orders enable row level security;
alter table public.gd_order_events enable row level security;
alter table public.gd_memories enable row level security;
create policy own_orders on public.gd_orders for select to authenticated using(owner_id = (select auth.uid()) or gd_private.is_admin());
create policy own_events on public.gd_order_events for select to authenticated using(exists(select 1 from public.gd_orders o where o.id=order_id and (o.owner_id=(select auth.uid()) or gd_private.is_admin())));
create policy own_memories on public.gd_memories for select to authenticated using(owner_id=(select auth.uid()));
grant select on public.gd_orders,public.gd_order_events,public.gd_memories to authenticated;
revoke insert,update,delete on public.gd_orders,public.gd_order_events,public.gd_memories from anon,authenticated;

create function gd_private.touch_version() returns trigger language plpgsql set search_path = '' as $$
begin new.version := old.version + 1; return new; end;
$$;
create trigger shop_version before update on public.gd_shop for each row execute function gd_private.touch_version();
create trigger product_version before update on public.gd_products for each row execute function gd_private.touch_version();
create trigger shipping_version before update on public.gd_shipping for each row execute function gd_private.touch_version();
commit;

-- 202610090002_orders.sql
begin;
create function public.gd_create_order(p_request jsonb) returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  uid uuid := auth.uid(); rid uuid; existing public.gd_orders;
  cfg public.gd_shop; delivery public.gd_shipping; product public.gd_products;
  line jsonb; lines jsonb := '[]'; seen integer[] := '{}'; qty integer; pid integer;
  amount bigint := 0; day date; phone text; message text; name text; address text; pay text;
  result public.gd_orders; body_hash text;
begin
  if uid is null then raise exception 'AUTH_REQUIRED'; end if;
  if jsonb_typeof(p_request) <> 'object' or length(p_request::text)>16000 or p_request->>'website' <> '' then raise exception 'INVALID_ORDER'; end if;
  rid := (p_request->>'requestId')::uuid;
  if rid is null or p_request->>'requestId' !~* '^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$' then raise exception 'INVALID_REQUEST_ID'; end if;
  -- Serialize retries of one intent before checking/inserting. Never trust submitted price/total.
  perform pg_advisory_xact_lock(hashtextextended(rid::text,0));
  body_hash := encode(sha256(convert_to(p_request::text,'UTF8')),'hex');
  select * into existing from public.gd_orders where id=rid;
  if found then
    if existing.owner_id <> uid or existing.request_body->>'hash' <> body_hash then raise exception 'IDEMPOTENCY_CONFLICT'; end if;
    return to_jsonb(existing) - 'request_body';
  end if;
  perform pg_advisory_xact_lock(hashtextextended('customer:'||uid::text,0));
  if (select count(*) from public.gd_orders where owner_id=uid and created_at>now()-interval '10 minutes')>=5
    or (select count(*) from public.gd_orders where owner_id=uid and created_at>now()-interval '1 day')>=30 then raise exception 'ORDER_RATE_LIMIT'; end if;
  select * into cfg from public.gd_shop where id=1 for share;
  if not cfg.accepting_orders then raise exception 'SHOP_CLOSED'; end if;
  if p_request->'consent' is distinct from 'true'::jsonb then raise exception 'CONSENT_REQUIRED'; end if;
  name := trim(p_request->>'name'); address := trim(p_request->>'address'); message := coalesce(trim(p_request->>'message'),'');
  phone := regexp_replace(p_request->>'phone','[\s().-]','','g');
  if name is null or length(name) not between 2 and 80 or address is null or length(address) not between 10 and 300 or length(message)>500 or phone is null or phone !~ '^(0|\+84)[35789][0-9]{8}$' then raise exception 'INVALID_CONTACT'; end if;
  if p_request->>'deliveryDate' is null or p_request->>'deliveryDate' !~ '^\d{4}-\d{2}-\d{2}$' then raise exception 'INVALID_DATE'; end if;
  day := (p_request->>'deliveryDate')::date;
  if day < (now() at time zone 'Asia/Ho_Chi_Minh')::date or day > (now() at time zone 'Asia/Ho_Chi_Minh')::date+90 then raise exception 'INVALID_DATE'; end if;
  if p_request->>'deliveryTime' is null or p_request->>'deliveryTime' not in ('Sáng · 9–12h','Chiều · 13–17h','Tối · 18–20h') then raise exception 'INVALID_TIME'; end if;
  select * into delivery from public.gd_shipping where id=(p_request->>'shippingId')::uuid and active for share;
  if not found then raise exception 'SHIPPING_UNAVAILABLE'; end if;
  if jsonb_typeof(p_request->'items') is distinct from 'array' or jsonb_array_length(p_request->'items') not between 1 and 20 then raise exception 'INVALID_ITEMS'; end if;
  for line in select value from jsonb_array_elements(p_request->'items') loop
    if jsonb_typeof(line->'id') <> 'number' or jsonb_typeof(line->'quantity') <> 'number' or line->>'id' !~ '^\d+$' or line->>'quantity' !~ '^\d+$' then raise exception 'INVALID_ITEMS'; end if;
    pid := (line->>'id')::integer; qty := (line->>'quantity')::integer;
    if pid=any(seen) or qty not between 1 and 20 then raise exception 'INVALID_ITEMS'; end if;
    seen := array_append(seen,pid);
    select * into product from public.gd_products where id=pid and active for share;
    if not found then raise exception 'PRODUCT_UNAVAILABLE'; end if;
    amount := amount + product.price::bigint * qty;
    lines := lines || jsonb_build_array(jsonb_build_object('id',product.id,'name',product.name,'price',product.price,'quantity',qty,'image',product.image));
  end loop;
  if jsonb_typeof(p_request->'expectedTotal') is distinct from 'number' or p_request->>'expectedTotal' !~ '^\d+$' or (p_request->>'expectedTotal')::bigint <> amount+delivery.fee then raise exception 'PRICE_CHANGED'; end if;
  pay := p_request->>'paymentMethod';
  if pay is null or pay not in ('COD','VIETQR') or (pay='COD' and not cfg.cod_enabled) or (pay='VIETQR' and not cfg.transfer_enabled) then raise exception 'PAYMENT_UNAVAILABLE'; end if;
  insert into public.gd_orders(id,owner_id,reference,request_body,recipient_name,recipient_phone,address,card_message,delivery_date,delivery_time,items,subtotal,shipping,total,payment_method,bank)
  values(rid,uid,'GD-'||upper(substr(replace(rid::text,'-',''),1,16)),jsonb_build_object('hash',body_hash),name,phone,address,message,day,p_request->>'deliveryTime',lines,amount,
    jsonb_build_object('id',delivery.id,'name',delivery.name,'area',delivery.area,'fee',delivery.fee),amount+delivery.fee,pay,
    case when pay='VIETQR' then jsonb_build_object('bin',cfg.bank_bin,'account',cfg.bank_account,'bankName',cfg.bank_name,'accountName',cfg.account_name) end)
  returning * into result;
  insert into public.gd_order_events(order_id,actor_id,event) values(rid,uid,'Đã tạo yêu cầu đặt hoa');
  return to_jsonb(result) - 'request_body';
end;
$$;
revoke execute on function public.gd_create_order(jsonb) from public,anon;
grant execute on function public.gd_create_order(jsonb) to authenticated;

create function public.gd_update_order(p_id uuid,p_version integer,p_status text,p_payment text,p_note text) returns jsonb language plpgsql security definer set search_path = '' as $$
declare current public.gd_orders; first_flower jsonb;
begin
  if not gd_private.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if length(coalesce(p_note,''))>500 then raise exception 'INVALID_NOTE'; end if;
  select * into current from public.gd_orders where id=p_id for update;
  if not found then raise exception 'NOT_FOUND'; end if;
  if current.version is distinct from p_version then raise exception 'VERSION_CONFLICT'; end if;
  if p_status is null or p_payment is null then raise exception 'INVALID_STATUS'; end if;
  if p_status<>current.status and not (
    (current.status='PENDING' and p_status in ('CONFIRMED','CANCELLED')) or
    (current.status='CONFIRMED' and p_status in ('PREPARING','CANCELLED')) or
    (current.status='PREPARING' and p_status in ('SHIPPING','CANCELLED')) or
    (current.status='SHIPPING' and p_status in ('DELIVERED','CANCELLED'))
  ) then raise exception 'INVALID_TRANSITION'; end if;
  if p_payment<>current.payment_status then
    if not ((current.payment_status='UNPAID' and p_payment='PAID' and p_status<>'CANCELLED') or (current.payment_status='PAID' and p_payment='REFUNDED')) then raise exception 'INVALID_PAYMENT_TRANSITION'; end if;
    if length(trim(coalesce(p_note,'')))<5 then raise exception 'PAYMENT_EVIDENCE_REQUIRED'; end if;
  end if;
  update public.gd_orders set status=p_status,payment_status=p_payment,version=version+1,updated_at=now() where id=p_id returning * into current;
  insert into public.gd_order_events(order_id,actor_id,event,note) values(p_id,auth.uid(),p_status||' · '||p_payment,coalesce(trim(p_note),''));
  if p_status='DELIVERED' and p_payment='PAID' then
    first_flower := current.items->0;
    insert into public.gd_memories(order_id,owner_id,flower_name,flower_image)
      values(p_id,current.owner_id,first_flower->>'name',first_flower->>'image') on conflict(order_id) do nothing;
  end if;
  if p_payment='REFUNDED' or p_status='CANCELLED' then
    update public.gd_memories set share_token=null,listed=false,revoked=true where order_id=p_id;
  end if;
  return to_jsonb(current) - 'request_body';
end;
$$;
revoke execute on function public.gd_update_order(uuid,integer,text,text,text) from public,anon;
grant execute on function public.gd_update_order(uuid,integer,text,text,text) to authenticated;

create function public.gd_share_memory(p_id uuid,p_visibility text,p_signature text default '') returns jsonb language plpgsql security definer set search_path = '' as $$
declare memory public.gd_memories; card text; result public.gd_memories;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  select * into memory from public.gd_memories where id=p_id and owner_id=auth.uid() for update;
  if not found then raise exception 'NOT_FOUND'; end if;
  if p_visibility is null or p_visibility not in ('PRIVATE','LINK','GARDEN') or length(coalesce(p_signature,''))>80 then raise exception 'INVALID_SHARING'; end if;
  if p_visibility='PRIVATE' then
    update public.gd_memories set share_token=null,listed=false,message='',signature='' where id=p_id returning * into result;
  else
    select o.card_message into card from public.gd_orders o where o.id=memory.order_id and o.status='DELIVERED' and o.payment_status='PAID';
    if not found or memory.revoked or length(trim(card))=0 then raise exception 'MEMORY_UNAVAILABLE'; end if;
    update public.gd_memories set message=card,signature=coalesce(trim(p_signature),''),share_token=coalesce(share_token,gen_random_uuid()),listed=(p_visibility='GARDEN') where id=p_id returning * into result;
  end if;
  return to_jsonb(result);
end;
$$;
revoke execute on function public.gd_share_memory(uuid,text,text) from public,anon;
grant execute on function public.gd_share_memory(uuid,text,text) to authenticated;

create function public.gd_public_memory(p_token uuid) returns jsonb language sql stable security definer set search_path = '' as $$
  select jsonb_build_object('token',share_token,'message',message,'signature',signature,'flowerName',flower_name,'flowerImage',flower_image,'createdAt',created_at)
    from public.gd_memories where share_token=p_token and not revoked;
$$;
create function public.gd_garden(p_before timestamptz default null,p_before_id uuid default null,p_limit integer default 24) returns jsonb language sql stable security definer set search_path = '' as $$
  select coalesce(jsonb_agg(jsonb_build_object('token',share_token,'id',id,'message',message,'signature',signature,'flowerName',flower_name,'flowerImage',flower_image,'createdAt',created_at) order by created_at desc,id desc),'[]'::jsonb)
  from (select * from public.gd_memories where listed and not revoked
    and (p_before is null or (created_at,id) < (p_before,coalesce(p_before_id,'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid)))
    order by created_at desc,id desc limit greatest(1,least(coalesce(p_limit,24),48))) m;
$$;
revoke execute on function public.gd_public_memory(uuid),public.gd_garden(timestamptz,uuid,integer) from public;
grant execute on function public.gd_public_memory(uuid),public.gd_garden(timestamptz,uuid,integer) to anon,authenticated;

create function public.gd_memory_count() returns bigint language sql stable security definer set search_path = '' as $$
  select count(*) from public.gd_memories where not revoked;
$$;
revoke execute on function public.gd_memory_count() from public;
grant execute on function public.gd_memory_count() to anon,authenticated;

-- Run daily using Supabase Cron; only the database owner can invoke this retention job.
create function public.gd_expire_contacts() returns bigint language plpgsql security definer set search_path = '' as $$
declare affected bigint;
begin
  update public.gd_orders set recipient_name=null,recipient_phone=null,address=null,contacts_erased_at=now()
    where status in ('DELIVERED','CANCELLED') and updated_at<now()-interval '90 days' and contacts_erased_at is null;
  get diagnostics affected=row_count; return affected;
end;
$$;
revoke execute on function public.gd_expire_contacts() from public,anon,authenticated;
commit;

-- 202610090003_catalog.sql
begin;
insert into public.gd_products(id,name,occasion,price,stems,description,image,featured) values
(1,'Nắng dịu','Chúc mừng',390000,'Cúc trắng, cúc vàng','Một bó cúc nhỏ, trong trẻo như một lời chúc bình an.','/flowers/bouquet_1.webp',true),
(2,'Khúc hồng','Tình yêu',490000,'Cẩm chướng hồng','Những cánh cẩm chướng xếp mềm, dành cho lời cảm ơn chưa nói.','/flowers/bouquet_2.webp',true),
(3,'Lời thì thầm','Sinh nhật',450000,'Hồng chùm, lá bạc','Sắc hồng nhẹ cùng những nhánh lá, ôm trọn một ngày vui.','/flowers/bouquet_3.webp',false),
(4,'Tình ca','Cưới hỏi',690000,'Hồng kem, eucalyptus','Một chút cổ điển, một chút dịu dàng cho ngày đặc biệt.','/flowers/bouquet_4.webp',false),
(5,'Mộng hoa','Cưới hỏi',590000,'Ly hồng, hoa phụ','Hoa ly kiêu hãnh giữa những cánh hoa nhỏ đầy duyên dáng.','/flowers/bouquet_5.webp',false),
(6,'Giấc mơ mẫu đơn','Tình yêu',890000,'Mẫu đơn hồng','Mẫu đơn bung nở, mềm mại và đầy đặn như một cái ôm.','/flowers/bouquet_6.webp',true),
(7,'Má hồng','Tình yêu',550000,'Hồng phấn','Một bảng màu êm dịu, dành cho người khiến bạn mỉm cười.','/flowers/bouquet_7.webp',false),
(8,'Nhớ thương','Tình yêu',650000,'Hồng đỏ, giấy vintage','Hồng đỏ sâu được gói trong giấy mộc, để lời yêu thêm ấm.','/flowers/bouquet_8.webp',true),
(9,'Giai điệu vườn','Sinh nhật',520000,'Hoa phối sắc pastel','Một khu vườn nhỏ với những sắc màu vui tươi vừa đủ.','/flowers/bouquet_9.webp',false),
(10,'Hồng nhung','Tình yêu',790000,'Hồng đỏ nhung','Màu đỏ nồng nàn, cho một lời thương thật rõ ràng.','/flowers/bouquet_10.webp',false),
(11,'Nắng mùa hè','Sinh nhật',480000,'Hoa vàng phối','Gói một chút nắng để ngày của người nhận sáng hơn.','/flowers/bouquet_11.webp',false),
(12,'Khoảng trời xanh','Chúc mừng',620000,'Phi yến xanh','Một mảng trời dịu mát, dành cho những khởi đầu mới.','/flowers/bouquet_12.webp',false),
(13,'Mẫu đơn kiêu sa','Cưới hỏi',950000,'Mẫu đơn, hoa phụ','Những cánh mẫu đơn nhiều lớp cho khoảnh khắc đáng nhớ.','/flowers/bouquet_13.webp',false),
(14,'Lời hẹn tulip','Tình yêu',720000,'Tulip hồng','Tulip thanh thoát, nói một lời hẹn nhẹ nhàng mà chân thành.','/flowers/bouquet_14.webp',false),
(15,'Hòa nhịp','Cưới hỏi',850000,'Hồng đỏ, hồng trắng','Đỏ và trắng đứng cạnh nhau, như hai người cùng chung nhịp.','/flowers/bouquet_15.webp',false),
(16,'Đồng hoa','Chúc mừng',420000,'Cúc phối màu','Một bó hoa phóng khoáng với tinh thần của buổi sớm ngoài đồng.','/flowers/bouquet_16.webp',false),
(17,'Bình yên','Chúc mừng',580000,'Cẩm tú cầu xanh','Cẩm tú cầu xanh nhạt, món quà dành cho một ngày cần bình yên.','/flowers/bouquet_17.webp',false),
(18,'Ngày rực rỡ','Sinh nhật',460000,'Đồng tiền vàng','Những bông đồng tiền tươi sáng, gửi niềm vui thật giản đơn.','/flowers/bouquet_18.webp',false),
(19,'Tinh khôi','Chúc mừng',640000,'Ly trắng','Sắc trắng trang nhã, gửi một lời chúc đầy trân trọng.','/flowers/bouquet_19.webp',false),
(20,'Ôm dịu dàng','Tình yêu',560000,'Hoa hồng phấn, eucalyptus','Màu phấn mềm và hương lá mát, một cái ôm không cần lời.','/flowers/bouquet_20.webp',false)
on conflict(id) do nothing;
select setval('public.gd_products_id_seq',(select max(id) from public.gd_products));
commit;

-- 202610090004_audit.sql
begin;
-- Supabase may apply default table privileges; make the intended grants explicit.
revoke all on public.gd_admins,public.gd_orders,public.gd_order_events,public.gd_memories from anon,authenticated;
grant select on public.gd_admins,public.gd_orders,public.gd_order_events,public.gd_memories to authenticated;
revoke all on public.gd_shop,public.gd_products,public.gd_shipping from anon,authenticated;
grant select on public.gd_shop,public.gd_products,public.gd_shipping to anon,authenticated;
grant update on public.gd_shop to authenticated;
grant insert,update on public.gd_products,public.gd_shipping to authenticated;

create table public.gd_admin_audit (
  id bigint generated always as identity primary key,
  actor_id uuid,
  entity text not null,
  entity_id text not null,
  action text not null,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);
alter table public.gd_admin_audit enable row level security;
revoke all on public.gd_admin_audit from anon,authenticated;
grant select on public.gd_admin_audit to authenticated;
create policy audit_admin on public.gd_admin_audit for select to authenticated using(gd_private.is_admin());
create function gd_private.audit_config() returns trigger language plpgsql security definer set search_path='' as $$
begin
  insert into public.gd_admin_audit(actor_id,entity,entity_id,action,before_data,after_data)
    values(auth.uid(),tg_table_name,new.id::text,tg_op,case when tg_op='UPDATE' then to_jsonb(old) end,to_jsonb(new));
  return new;
end;
$$;
revoke execute on function gd_private.audit_config() from public,anon,authenticated;
create trigger shop_audit after update on public.gd_shop for each row execute function gd_private.audit_config();
create trigger product_audit after insert or update on public.gd_products for each row execute function gd_private.audit_config();
create trigger shipping_audit after insert or update on public.gd_shipping for each row execute function gd_private.audit_config();
commit;

-- 202610090005_environment.sql
begin;
create table gd_private.runtime (
  id integer primary key check(id=1),
  environment text not null check(environment in ('production','staging','local')),
  project_ref text check(project_ref ~ '^[a-z0-9]{20}$'),
  check((environment='local' and project_ref is null) or (environment<>'local' and project_ref is not null))
);
insert into gd_private.runtime values(1,'production','ztzpipgptticvliotbsc');
revoke all on gd_private.runtime from public,anon,authenticated;

create function gd_private.freeze_environment() returns trigger language plpgsql security definer set search_path='' as $$
begin
  if tg_op='DELETE' or (exists(select 1 from public.gd_orders) and (new.environment,new.project_ref) is distinct from (old.environment,old.project_ref)) then raise exception 'ENVIRONMENT_LOCKED'; end if;
  return new;
end;
$$;
revoke execute on function gd_private.freeze_environment() from public,anon,authenticated;
create trigger freeze_environment before update or delete on gd_private.runtime for each row execute function gd_private.freeze_environment();

create function public.gd_environment() returns jsonb language sql stable security definer set search_path='' as $$
  select jsonb_build_object('environment',environment,'projectRef',project_ref) from gd_private.runtime where id=1;
$$;
revoke execute on function public.gd_environment() from public;
grant execute on function public.gd_environment() to anon,authenticated;

alter table public.gd_orders add column is_test boolean not null default false;
alter table public.gd_memories add column is_test boolean not null default false;

create function gd_private.classify_order() returns trigger language plpgsql security definer set search_path='' as $$
begin
  if tg_op='INSERT' then
    select environment<>'production' into new.is_test from gd_private.runtime where id=1;
    if new.is_test is null then raise exception 'ENVIRONMENT_REQUIRED'; end if;
  elsif new.is_test is distinct from old.is_test then raise exception 'ORDER_KIND_IMMUTABLE'; end if;
  return new;
end;
$$;
revoke execute on function gd_private.classify_order() from public,anon,authenticated;
create trigger classify_order before insert or update on public.gd_orders for each row execute function gd_private.classify_order();

create function gd_private.classify_memory() returns trigger language plpgsql security definer set search_path='' as $$
begin
  if tg_op='INSERT' then
    -- Missing orders only occur in an isolated benchmark that deliberately removes its FK.
    new.is_test := coalesce((select is_test from public.gd_orders where id=new.order_id),true);
  elsif new.is_test is distinct from old.is_test then raise exception 'MEMORY_KIND_IMMUTABLE'; end if;
  return new;
end;
$$;
revoke execute on function gd_private.classify_memory() from public,anon,authenticated;
create trigger classify_memory before insert or update on public.gd_memories for each row execute function gd_private.classify_memory();

create or replace function public.gd_public_memory(p_token uuid) returns jsonb language sql stable security definer set search_path='' as $$
  select jsonb_build_object('token',share_token,'message',message,'signature',signature,'flowerName',flower_name,'flowerImage',flower_image,'createdAt',created_at)
  from public.gd_memories where share_token=p_token and not revoked
    and (not is_test or (select environment from gd_private.runtime where id=1)<>'production');
$$;
create or replace function public.gd_garden(p_before timestamptz default null,p_before_id uuid default null,p_limit integer default 24) returns jsonb language sql stable security definer set search_path='' as $$
  select coalesce(jsonb_agg(jsonb_build_object('token',share_token,'id',id,'message',message,'signature',signature,'flowerName',flower_name,'flowerImage',flower_image,'createdAt',created_at) order by created_at desc,id desc),'[]'::jsonb)
  from (select * from public.gd_memories where listed and not revoked
    and (not is_test or (select environment from gd_private.runtime where id=1)<>'production')
    and (p_before is null or (created_at,id)<(p_before,coalesce(p_before_id,'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid)))
    order by created_at desc,id desc limit greatest(1,least(coalesce(p_limit,24),48))) m;
$$;
create or replace function public.gd_memory_count() returns bigint language sql stable security definer set search_path='' as $$
  select count(*) from public.gd_memories where not revoked and not is_test;
$$;

-- Future finance dashboards must read this projection, excluding all test orders.
create view gd_private.real_orders as select * from public.gd_orders where not is_test;
revoke all on gd_private.real_orders from public,anon,authenticated;
commit;

-- Only on the new staging project tgvozhrkolcpszyyrgth, after migrations 001–005.
begin;
do $$
begin
  if exists(select 1 from gd_private.runtime where environment='staging' and project_ref='tgvozhrkolcpszyyrgth') then return; end if;
  if exists(select 1 from public.gd_orders) or exists(select 1 from public.gd_admins) or exists(select 1 from auth.users) then raise exception 'STAGING_REQUIRES_EMPTY_PROJECT'; end if;
  update gd_private.runtime set environment='staging',project_ref='tgvozhrkolcpszyyrgth' where id=1;
  update public.gd_shop set accepting_orders=false;
end;
$$;
select public.gd_environment() as runtime;
commit;
