export const occasions = [
  "Tất cả",
  "Sinh nhật",
  "Tình yêu",
  "Chúc mừng",
  "Cưới hỏi",
];

const flowers = [
  [
    "Nắng dịu",
    "Chúc mừng",
    390000,
    "Cúc trắng, cúc vàng",
    "Một bó cúc nhỏ, trong trẻo như một lời chúc bình an.",
  ],
  [
    "Khúc hồng",
    "Tình yêu",
    490000,
    "Cẩm chướng hồng",
    "Những cánh cẩm chướng xếp mềm, dành cho lời cảm ơn chưa nói.",
  ],
  [
    "Lời thì thầm",
    "Sinh nhật",
    450000,
    "Hồng chùm, lá bạc",
    "Sắc hồng nhẹ cùng những nhánh lá, ôm trọn một ngày vui.",
  ],
  [
    "Tình ca",
    "Cưới hỏi",
    690000,
    "Hồng kem, eucalyptus",
    "Một chút cổ điển, một chút dịu dàng cho ngày đặc biệt.",
  ],
  [
    "Mộng hoa",
    "Cưới hỏi",
    590000,
    "Ly hồng, hoa phụ",
    "Hoa ly kiêu hãnh giữa những cánh hoa nhỏ đầy duyên dáng.",
  ],
  [
    "Giấc mơ mẫu đơn",
    "Tình yêu",
    890000,
    "Mẫu đơn hồng",
    "Mẫu đơn bung nở, mềm mại và đầy đặn như một cái ôm.",
  ],
  [
    "Má hồng",
    "Tình yêu",
    550000,
    "Hồng phấn",
    "Một bảng màu êm dịu, dành cho người khiến bạn mỉm cười.",
  ],
  [
    "Nhớ thương",
    "Tình yêu",
    650000,
    "Hồng đỏ, giấy vintage",
    "Hồng đỏ sâu được gói trong giấy mộc, để lời yêu thêm ấm.",
  ],
  [
    "Giai điệu vườn",
    "Sinh nhật",
    520000,
    "Hoa phối sắc pastel",
    "Một khu vườn nhỏ với những sắc màu vui tươi vừa đủ.",
  ],
  [
    "Hồng nhung",
    "Tình yêu",
    790000,
    "Hồng đỏ nhung",
    "Màu đỏ nồng nàn, cho một lời thương thật rõ ràng.",
  ],
  [
    "Nắng mùa hè",
    "Sinh nhật",
    480000,
    "Hoa vàng phối",
    "Gói một chút nắng để ngày của người nhận sáng hơn.",
  ],
  [
    "Khoảng trời xanh",
    "Chúc mừng",
    620000,
    "Phi yến xanh",
    "Một mảng trời dịu mát, dành cho những khởi đầu mới.",
  ],
  [
    "Mẫu đơn kiêu sa",
    "Cưới hỏi",
    950000,
    "Mẫu đơn, hoa phụ",
    "Những cánh mẫu đơn nhiều lớp cho khoảnh khắc đáng nhớ.",
  ],
  [
    "Lời hẹn tulip",
    "Tình yêu",
    720000,
    "Tulip hồng",
    "Tulip thanh thoát, nói một lời hẹn nhẹ nhàng mà chân thành.",
  ],
  [
    "Hòa nhịp",
    "Cưới hỏi",
    850000,
    "Hồng đỏ, hồng trắng",
    "Đỏ và trắng đứng cạnh nhau, như hai người cùng chung nhịp.",
  ],
  [
    "Đồng hoa",
    "Chúc mừng",
    420000,
    "Cúc phối màu",
    "Một bó hoa phóng khoáng với tinh thần của buổi sớm ngoài đồng.",
  ],
  [
    "Bình yên",
    "Chúc mừng",
    580000,
    "Cẩm tú cầu xanh",
    "Cẩm tú cầu xanh nhạt, món quà dành cho một ngày cần bình yên.",
  ],
  [
    "Ngày rực rỡ",
    "Sinh nhật",
    460000,
    "Đồng tiền vàng",
    "Những bông đồng tiền tươi sáng, gửi niềm vui thật giản đơn.",
  ],
  [
    "Tinh khôi",
    "Chúc mừng",
    640000,
    "Ly trắng",
    "Sắc trắng trang nhã, gửi một lời chúc đầy trân trọng.",
  ],
  [
    "Ôm dịu dàng",
    "Tình yêu",
    560000,
    "Hoa hồng phấn, eucalyptus",
    "Màu phấn mềm và hương lá mát, một cái ôm không cần lời.",
  ],
];

export const products = flowers.map(
  ([name, occasion, price, stems, description], i) => ({
    id: i + 1,
    name,
    occasion,
    price,
    stems,
    description,
    image: `/flowers/bouquet_${i + 1}.webp`,
    featured: [1, 2, 6, 8].includes(i + 1),
  }),
);
export const money = (value) =>
  new Intl.NumberFormat("vi-VN", {
    style: "currency",
    currency: "VND",
    maximumFractionDigits: 0,
  }).format(value);
