begin;
create schema if not exists gd_private;
revoke all on schema gd_private from public;

create table public.gd_admins (user_id uuid primary key references auth.users(id) on delete cascade);
alter table public.gd_admins enable row level security;
create policy admin_self on public.gd_admins for select to authenticated using (user_id = (select auth.uid()));
grant select on public.gd_admins to authenticated;
revoke insert, update, delete on public.gd_admins from anon, authenticated;
create function gd_private.is_admin() returns boolean language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.gd_admins where user_id = auth.uid());
$$;
grant usage on schema gd_private to authenticated;
grant execute on function gd_private.is_admin() to authenticated;
revoke execute on function gd_private.is_admin() from public, anon;

create table public.gd_shop (
  id integer primary key check (id = 1),
  name text not null check(length(name) between 2 and 80),
  phone text not null check(phone ~ '^(0|\+84)[35789][0-9]{8}$'),
  about text not null default '' check(length(about) <= 1000),
  accepting_orders boolean not null default false,
  cod_enabled boolean not null default true,
  transfer_enabled boolean not null default false,
  bank_bin text not null default '' check(bank_bin = '' or bank_bin ~ '^[0-9]{6}$'),
  bank_account text not null default '' check(bank_account = '' or bank_account ~ '^[0-9A-Za-z]{4,32}$'),
  bank_name text not null default '' check(length(bank_name) <= 80),
  account_name text not null default '' check(length(account_name) <= 100),
  version integer not null default 1,
  check(not transfer_enabled or (bank_bin <> '' and bank_account <> '' and account_name <> '')),
  check(not accepting_orders or cod_enabled or transfer_enabled)
);
insert into public.gd_shop(id,name,phone,about) values(1,'Garden Dreams','0832345780','Hoa mang lời thương.');
create table public.gd_products (
  id integer generated by default as identity primary key,
  name text not null check(length(name) between 2 and 100),
  occasion text not null check(occasion in ('Sinh nhật','Tình yêu','Chúc mừng','Cưới hỏi')),
  price integer not null check(price between 1000 and 100000000),
  stems text not null check(length(stems) <= 200),
  description text not null check(length(description) <= 1000),
  image text not null check(length(image) <= 500 and (image ~ '^/flowers/[a-zA-Z0-9_.-]+$' or image ~ '^https://')),
  active boolean not null default true,
  featured boolean not null default false,
  version integer not null default 1
);
create table public.gd_shipping (
  id uuid primary key default gen_random_uuid(),
  name text not null check(length(name) between 2 and 80),
  area text not null check(length(area) between 2 and 200),
  fee integer not null check(fee between 0 and 10000000),
  active boolean not null default false,
  version integer not null default 1
);
insert into public.gd_shipping(name,area,fee) values('Giao hoa theo lịch','Chưa cấu hình khu vực giao',0);
alter table public.gd_shop enable row level security;
alter table public.gd_products enable row level security;
alter table public.gd_shipping enable row level security;
create policy shop_read on public.gd_shop for select to anon, authenticated using (true);
create policy shop_admin on public.gd_shop for update to authenticated using (gd_private.is_admin()) with check (gd_private.is_admin());
create policy product_read on public.gd_products for select to anon, authenticated using(active or gd_private.is_admin());
create policy product_admin on public.gd_products for all to authenticated using(gd_private.is_admin()) with check(gd_private.is_admin());
create policy shipping_read on public.gd_shipping for select to anon, authenticated using(active or gd_private.is_admin());
create policy shipping_admin on public.gd_shipping for all to authenticated using(gd_private.is_admin()) with check(gd_private.is_admin());
grant select on public.gd_shop, public.gd_products, public.gd_shipping to anon, authenticated;
grant update on public.gd_shop to authenticated;
grant insert,update,delete on public.gd_products,public.gd_shipping to authenticated;
grant usage,select on sequence public.gd_products_id_seq to authenticated;
-- anon must be able to evaluate the read policy without accessing any admin rows.
grant usage on schema gd_private to anon;
grant execute on function gd_private.is_admin() to anon;

create table public.gd_orders (
  id uuid primary key,
  owner_id uuid not null references auth.users(id),
  reference text not null unique,
  request_body jsonb not null,
  recipient_name text,
  recipient_phone text,
  address text,
  card_message text not null default '',
  delivery_date date not null,
  delivery_time text not null,
  items jsonb not null,
  subtotal bigint not null check(subtotal >= 0),
  shipping jsonb not null,
  total bigint not null check(total >= 0),
  payment_method text not null check(payment_method in ('COD','VIETQR')),
  bank jsonb,
  status text not null default 'PENDING' check(status in ('PENDING','CONFIRMED','PREPARING','SHIPPING','DELIVERED','CANCELLED')),
  payment_status text not null default 'UNPAID' check(payment_status in ('UNPAID','PAID','REFUNDED')),
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  contacts_erased_at timestamptz
);
create index gd_orders_owner_cursor on public.gd_orders(owner_id, created_at desc, id desc);
create index gd_orders_admin_cursor on public.gd_orders(created_at desc, id desc);
create table public.gd_order_events (
  id bigint generated always as identity primary key,
  order_id uuid not null references public.gd_orders(id),
  actor_id uuid references auth.users(id),
  event text not null,
  note text not null default '',
  created_at timestamptz not null default now()
);
create index gd_events_order on public.gd_order_events(order_id,id);
create table public.gd_memories (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.gd_orders(id),
  owner_id uuid not null references auth.users(id),
  message text not null default '',
  signature text not null default '' check(length(signature) <= 80),
  flower_name text not null,
  flower_image text not null,
  share_token uuid unique,
  listed boolean not null default false,
  revoked boolean not null default false,
  created_at timestamptz not null default now(),
  check(not listed or share_token is not null)
);
create index gd_memories_garden_cursor on public.gd_memories(created_at desc,id desc) where listed and not revoked;
create index gd_memories_owner on public.gd_memories(owner_id,created_at desc,id desc);
alter table public.gd_orders enable row level security;
alter table public.gd_order_events enable row level security;
alter table public.gd_memories enable row level security;
create policy own_orders on public.gd_orders for select to authenticated using(owner_id = (select auth.uid()) or gd_private.is_admin());
create policy own_events on public.gd_order_events for select to authenticated using(exists(select 1 from public.gd_orders o where o.id=order_id and (o.owner_id=(select auth.uid()) or gd_private.is_admin())));
create policy own_memories on public.gd_memories for select to authenticated using(owner_id=(select auth.uid()));
grant select on public.gd_orders,public.gd_order_events,public.gd_memories to authenticated;
revoke insert,update,delete on public.gd_orders,public.gd_order_events,public.gd_memories from anon,authenticated;

create function gd_private.touch_version() returns trigger language plpgsql set search_path = '' as $$
begin new.version := old.version + 1; return new; end;
$$;
create trigger shop_version before update on public.gd_shop for each row execute function gd_private.touch_version();
create trigger product_version before update on public.gd_products for each row execute function gd_private.touch_version();
create trigger shipping_version before update on public.gd_shipping for each row execute function gd_private.touch_version();
commit;
